---
apiVersion: v1
kind: Namespace
metadata:
  name: netology
  labels:
    name: netology
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  read-write-app
  namespace: netology
  labels:
    app:  rw-data
spec:
  selector:
    matchLabels:
      app: rw-data
  replicas: 1
  template:
    metadata:
      labels:
        app:  rw-data
    spec:
      containers:
      - name:  writer
        image:  busybox
        command: [ 'sh', '-c', 'while true; do echo "$(date) - ok" >> "/data/file"; sleep 5; done']
        resources:
          requests:
            cpu: 1m
            memory: 20Mi
          limits:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: data
          mountPath: /data

      - name: reader
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
        resources:
          requests:
            cpu: 1m
            memory: 20Mi
          limits:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: data
          mountPath: /data

      volumes:
        - name: data
          emptyDir: {}