---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dyn-pvc
  namespace: netology
  labels:
    app: test-vol2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-vol-app2
  namespace: netology
  labels:
    app:  test-vol-app2
spec:
  selector:
    matchLabels:
      app: test-vol-app2
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-vol-app2
    spec:
      containers:
      - name: worker
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
        resources:
          requests:
            cpu: 1m
            memory: 20Mi
          limits:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dyn-pvc

