---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
      initContainers:
      - name: init-nginx
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup netology-nginx.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for netology-nginx; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: netology-nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
