---
apiVersion: v1
kind: Namespace
metadata:
  name: netology
  labels:
    name: netology
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-port
  namespace: netology
data:
  HTTP_PORT: "8080"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-index
  namespace: netology
data:
  index.html: |
    <html>
    <head>
    </head>
    <body>
    index_file
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
          requests:
            memory: "20Mi"
            cpu: "1m"
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/share/nginx/html

      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: config-port
              key: HTTP_PORT
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "128Mi"
      volumes:
      - name: configmap-volume
        configMap:
          name: config-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: netology
spec:
  selector:
    app: config-app
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    nodePort: 31180
---
apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
  namespace: netology
spec:
  selector:
    app: config-app
  type: NodePort
  ports:
  - name: multitool
    protocol: TCP
    port: 8080
    nodePort: 31181
