---
apiVersion: v1
kind: Namespace
metadata:
  name: netology
  labels:
    name: netology
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-volume
  namespace: netology
data:
  index.html: |
    <html>
    <head>
    </head>
    <body>
    <p>my https web-site !!!</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-site
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-site
  template:
    metadata:
      labels:
        app: web-site
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
          requests:
            memory: "20Mi"
            cpu: "1m"
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: configmap-volume
        configMap:
          name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: web-site-svc
  namespace: netology
spec:
  selector:
    app: web-site
  type: ClusterIP
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls-web-site
  namespace: netology
type: kubernetes.io/tls
# The TLS secret must contain keys named 'tls.crt' and 'tls.key' that contain the certificate and private key to use for TLS.
data:
  tls.crt: |
    <cat tls.crt | base64>

  tls.key: |
    <cat tls.key | base64>

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-site-ingress
  namespace: netology
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - web-site.a148ru.ru
    secretName: secret-tls-web-site
  rules:
  - host: web-site.a148ru.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-site-svc
            port:
              number: 80
