---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-
  {{- .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathtype }}
        backend:
          service:
            name: {{ .Release.Name }}-
            {{- .Values.web.names.svc }}
            port:
              number: {{ .Values.ingress.port }}