---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-
  {{- .Values.db.names.secret }}
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPassword }}
  MYSQL_PASSWORD: {{ .Values.db.password }}
